<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

/**
 * Dữ liệu xe theo sheet "Thông tin xe" trong file Test_Phiếu đề xuất ghi nhận.xlsx (đồng bộ thủ công).
 */
class VehicleExcelSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'license_plate' => '51A-796.68',
                'owner_name' => 'Công ty CP Đầu tư Phát triển Giáo dục Hoàng Việt',
                'frame_engine_number' => "SK: RL4XW42G1E9409451\nSM: 1TR7720806",
                'type' => 'TOYOTA INNOVA - Nâu vàng',
                'year_manufactured' => 2014,
                'purchased_at' => '2014-02-01',
                'usage_expires_year' => null,
                'seat_count' => 8,
                'insurance_provider' => 'MIC',
                'insurance_policy_note' => "08g00 ngày 01/03/2026 - 08g00 ngày 01/03/2027",
                'insurance_expires_at' => '2027-03-01',
                'inspection_expires_at' => '2026-06-19',
                'road_fee_expires_at' => '2026-06-26',
                'registration_cycle_note' => 'Đăng kiểm 12 tháng/lần',
                'last_maintenance_at' => '2026-01-30',
                'maintenance_schedule_note' => '5.000 km (Tại Toyota Hùng Vương)',
                'caretaker_name' => 'Đỗ Mạnh Hùng',
                'caretaker_phone' => null,
                'notes' => null,
            ],
            [
                'license_plate' => '51A-832.43',
                'owner_name' => 'Công ty CP Đầu tư Phát triển Giáo dục Hoàng Việt',
                'frame_engine_number' => "SK: RN2BL4ZA4EC005748\nSM: B36858Z6",
                'type' => 'MAZDA 3BL AT - Đỏ',
                'year_manufactured' => 2014,
                'purchased_at' => '2014-04-01',
                'usage_expires_year' => null,
                'seat_count' => 5,
                'insurance_policy_note' => "14g00 ngày 01/03/2026 - 14g00 ngày 01/03/2027",
                'insurance_expires_at' => '2027-03-01',
                'inspection_expires_at' => null,
                'road_fee_expires_at' => null,
                'caretaker_name' => null,
                'caretaker_phone' => null,
                'notes' => 'Xe bàn giao Toàn Lực',
            ],
            [
                'license_plate' => '51H-360.95',
                'owner_name' => 'Công ty CP Văn hóa Giáo dục Việt Mỹ',
                'frame_engine_number' => "SK: RPXAB2RXGKV000233\nSM: 192120020VF20SUV",
                'type' => 'VINFAST LUX SA 2.0 - Nâu',
                'year_manufactured' => 2019,
                'purchased_at' => '2020-09-01',
                'seat_count' => 7,
                'insurance_policy_note' => "14g00 ngày 01/03/2026 - 14g00 ngày 01/03/2027",
                'insurance_expires_at' => '2027-03-01',
                'inspection_expires_at' => '2027-03-04',
                'road_fee_expires_at' => '2027-03-04',
                'caretaker_name' => 'Đỗ Mạnh Hùng',
                'caretaker_phone' => '0983931404',
            ],
            [
                'license_plate' => '51K-984.58',
                'owner_name' => 'Công ty CP Văn hóa Giáo dục Việt Mỹ',
                'frame_engine_number' => "SK: RLLV2CKA4PV012422\nSM: VFBALB236270104 / VFBALA236230093\nSerial Pin: V9L3094230624D0017",
                'type' => 'VINFAST VF9 PLUS - Xanh rêu',
                'year_manufactured' => 2023,
                'purchased_at' => '2023-12-01',
                'seat_count' => 6,
                'insurance_provider' => 'MIC',
                'insurance_policy_note' => '17g00 22/08/2025 - 16g59 22/08/2026',
                'insurance_expires_at' => '2026-08-22',
                'inspection_expires_at' => '2026-08-17',
                'road_fee_expires_at' => '2026-08-17',
                'last_maintenance_at' => '2026-03-06',
                'caretaker_name' => 'Dương Hoàng Trọng',
            ],
            [
                'license_plate' => '51B-513.01',
                'owner_name' => 'Công ty CP Văn hóa Giáo dục Việt Mỹ',
                'frame_engine_number' => "SK: RL3DLT6MMPTR55879\nSM: P7P35266DURATORQ4D225H",
                'type' => 'FORD TRANSIT - Bạc bạch kim',
                'year_manufactured' => 2023,
                'purchased_at' => '2023-08-01',
                'usage_expires_year' => 2043,
                'seat_count' => 16,
                'insurance_provider' => 'MIC',
                'insurance_policy_note' => "08g01 ngày 22/08/2025 - 08g01 ngày 22/08/2026",
                'insurance_expires_at' => '2026-08-22',
                'inspection_expires_at' => '2026-08-20',
                'road_fee_expires_at' => '2026-08-23',
                'registration_cycle_note' => 'Đăng kiểm 6 tháng/lần',
                'last_maintenance_at' => '2025-05-12',
                'maintenance_schedule_note' => '10.000 km/ 6 tháng (Tại Hãng Ford An Lạc)',
                'caretaker_name' => 'Bùi Trung Hiếu',
                'caretaker_phone' => '0907709149',
            ],
            [
                'license_plate' => '51B-513.82',
                'owner_name' => 'Công ty CP Văn hóa Giáo dục Việt Mỹ',
                'frame_engine_number' => "SK: RL3DLT6MMPTR55815\nSM: P5P22089DURATORQ4D225H",
                'type' => 'FORD TRANSIT - Bạc bạch kim',
                'year_manufactured' => 2023,
                'purchased_at' => '2023-08-01',
                'usage_expires_year' => 2043,
                'seat_count' => 16,
                'insurance_policy_note' => "08g01 ngày 22/08/2025 - 08g01 ngày 22/08/2026",
                'insurance_expires_at' => '2026-08-22',
                'inspection_expires_at' => '2026-08-20',
                'road_fee_expires_at' => '2026-08-23',
                'registration_cycle_note' => 'Đăng kiểm 6 tháng/lần',
                'last_maintenance_at' => '2025-05-12',
                'maintenance_schedule_note' => '10.000 km/ 6 tháng (Tại Hãng Ford An Lạc)',
                'caretaker_name' => 'Nguyễn Phương Vinh',
                'caretaker_phone' => '0903085373',
            ],
            [
                'license_plate' => '51B-519.77',
                'owner_name' => 'Công ty CP Văn hóa Giáo dục Việt Mỹ',
                'frame_engine_number' => "SK: RL3DLT6MMNAR33918\nSM: NAP69252DURATORQ4D225H",
                'type' => 'FORD TRANSIT - Bạc bạch kim',
                'year_manufactured' => 2022,
                'purchased_at' => '2022-10-01',
                'usage_expires_year' => 2042,
                'seat_count' => 16,
                'insurance_policy_note' => '00g00 ngày 05/12/2025 - 23g59 ngày 04/12/2026',
                'insurance_expires_at' => '2026-12-04',
                'inspection_expires_at' => '2026-05-25',
                'road_fee_expires_at' => '2026-05-31',
                'registration_cycle_note' => 'Đăng kiểm 6 tháng/lần',
                'last_maintenance_at' => '2025-09-08',
                'maintenance_schedule_note' => '10.000 km/ 6 tháng (Tại Hãng Ford An Lạc)',
                'caretaker_name' => 'Đỗ Mạnh Hùng',
                'caretaker_phone' => '0983931404',
            ],
            [
                'license_plate' => '51B-145.58',
                'owner_name' => 'Trường Tiểu học Dân lập Việt Mỹ',
                'frame_engine_number' => "SK: RL3MLTGMCERR33939\nSM: E8P37591DURATORQ4D243H",
                'type' => 'FORD TRANSIT - Bạc bạch kim',
                'year_manufactured' => 2014,
                'purchased_at' => null,
                'usage_expires_year' => 2034,
                'seat_count' => 16,
                'insurance_policy_note' => '10g38 ngày 26/11/2025 – 10g37 ngày 26/11/2026',
                'insurance_expires_at' => '2026-11-26',
                'inspection_expires_at' => '2026-08-08',
                'road_fee_expires_at' => '2026-08-08',
                'registration_cycle_note' => 'Đăng kiểm 6 tháng/lần',
                'last_maintenance_at' => '2026-02-07',
                'maintenance_schedule_note' => '10.000 km/ 1 năm (Tại Garage Thái Tỷ)',
                'caretaker_name' => 'Hoàng Việt Hưng',
                'caretaker_phone' => '0935088080',
            ],
            [
                'license_plate' => '51B-149.84',
                'owner_name' => 'Trường THCS Việt Mỹ',
                'frame_engine_number' => "SK: JTFSS22P700137596\nSM: 2KDA625226",
                'type' => 'TOYOTA HIACE - Bạc',
                'year_manufactured' => 2014,
                'purchased_at' => '2014-11-01',
                'usage_expires_year' => 2034,
                'seat_count' => 16,
                'insurance_policy_note' => '17g27 ngày 17/11/2025 – 17g27 ngày 17/11/2026',
                'insurance_expires_at' => '2026-11-17',
                'inspection_expires_at' => '2026-08-04',
                'road_fee_expires_at' => '2026-08-04',
                'registration_cycle_note' => 'Đăng kiểm 6 tháng/lần',
                'last_maintenance_at' => '2025-03-24',
                'maintenance_schedule_note' => '5.000 km (Tại Garage Thái Tỷ)',
                'caretaker_name' => 'Nguyễn Tấn Tài',
                'caretaker_phone' => '0866649771',
                'notes' => "Xe bàn giao cho Vũng Tàu",
            ],
            [
                'license_plate' => '53S-8452',
                'owner_name' => 'Công ty CP Đầu tư Phát triển Thương mại Viễn Đông',
                'frame_engine_number' => "SM: 2TR6944346\nSK: RL4RX13P2A9002980",
                'type' => 'TOYOTA HIACE TRH213L - Bạc',
                'year_manufactured' => 2010,
                'purchased_at' => '2010-01-01',
                'usage_expires_year' => 2030,
                'seat_count' => 10,
                'insurance_policy_note' => "08g00 ngày 08/09/2025 - 08g00 ngày 08/09/2026",
                'insurance_expires_at' => '2026-09-08',
                'inspection_expires_at' => '2026-07-20',
                'road_fee_expires_at' => '2025-12-27',
                'registration_cycle_note' => 'Đăng kiểm 6 tháng/lần',
                'last_maintenance_at' => null,
                'maintenance_schedule_note' => '5.000 km (Tại Toyota Hùng Vương)',
                'caretaker_name' => 'Nguyễn Tấn Tài',
                'notes' => "Biển phụ: 51M-23494. Có hợp đồng thuê xe với TiH Dân lập Việt Mỹ hết hạn 2018.",
            ],
            [
                'license_plate' => '51K-574.66',
                'owner_name' => 'Công ty CP Giấy Toàn Lực',
                'frame_engine_number' => "SK: RLLV2CKA4PV006930\nSM: VFBALB232130596VFBALA232040527",
                'type' => 'VINFAST VF9 PLUS - Xám',
                'year_manufactured' => 2023,
                'purchased_at' => '2023-01-01',
                'seat_count' => 7,
                'insurance_provider' => 'PVI',
                'insurance_policy_note' => "09g00 ngày 02/06/2025 - 09g00 ngày 02/06/2026",
                'insurance_expires_at' => '2026-06-02',
                'inspection_expires_at' => '2026-05-22',
                'caretaker_name' => null,
                'notes' => 'Xe bàn giao Ban Tổng Giám đốc',
            ],
        ];

        foreach ($rows as $row) {
            $plate = $row['license_plate'];
            unset($row['license_plate']);
            $row['status'] = 'ready';
            $row['odometer_km'] = $row['odometer_km'] ?? 0;
            Vehicle::updateOrCreate(
                ['license_plate' => $plate],
                $row
            );
        }
    }
}
