import {
  AcademicCapIcon,
  BanknotesIcon,
  BellIcon,
  CalendarDaysIcon,
  CalendarIcon,
  ChartBarIcon,
  ClipboardDocumentListIcon,
  CubeIcon,
  CurrencyDollarIcon,
  FlagIcon,
  HomeIcon,
  MapPinIcon,
  PlusCircleIcon,
  QuestionMarkCircleIcon,
  ShieldCheckIcon,
  Squares2X2Icon,
  TagIcon,
  TruckIcon,
} from '@heroicons/vue/24/outline'

/** Khóa dùng trong `nav.js` → component icon outline 24px, stroke 1.5 */
export const NAV_ICON_MAP = {
  home: HomeIcon,
  hub: Squares2X2Icon,
  schedule: CalendarIcon,
  calendar: CalendarDaysIcon,
  requests: ClipboardDocumentListIcon,
  new_request: PlusCircleIcon,
  trips: TruckIcon,
  costs: CurrencyDollarIcon,
  cargo: CubeIcon,
  routes: MapPinIcon,
  students: AcademicCapIcon,
  payments: BanknotesIcon,
  reports: ChartBarIcon,
  pricing: TagIcon,
  help: QuestionMarkCircleIcon,
  roadmap: FlagIcon,
  notifications: BellIcon,
  audit: ShieldCheckIcon,
}
