import {
  AdjustmentsHorizontalIcon,
  BellIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ClipboardDocumentListIcon,
  Cog6ToothIcon,
  CubeIcon,
  CurrencyDollarIcon,
  FlagIcon,
  HomeIcon,
  KeyIcon,
  MapPinIcon,
  PlusCircleIcon,
  QuestionMarkCircleIcon,
  ShieldCheckIcon,
  TagIcon,
  RectangleStackIcon,
  TruckIcon,
  UserGroupIcon,
  UserIcon,
  UsersIcon,
  ViewColumnsIcon,
  WrenchScrewdriverIcon,
} from '@heroicons/vue/24/outline'

/** Khóa dùng trong `nav.js` → component icon outline 24px, stroke 1.5 */
export const NAV_ICON_MAP = {
  home: HomeIcon,
  calendar: CalendarDaysIcon,
  user: UserIcon,
  wrench: WrenchScrewdriverIcon,
  driver: TruckIcon,
  dispatcher: ViewColumnsIcon,
  requests: ClipboardDocumentListIcon,
  new_request: PlusCircleIcon,
  trips: TruckIcon,
  costs: CurrencyDollarIcon,
  cargo: CubeIcon,
  routes: MapPinIcon,
  resources: RectangleStackIcon,
  reports: ChartBarIcon,
  pricing: TagIcon,
  help: QuestionMarkCircleIcon,
  roadmap: FlagIcon,
  notifications: BellIcon,
  audit: ShieldCheckIcon,
  settings: Cog6ToothIcon,
  roles: UserGroupIcon,
  permissions: KeyIcon,
  user_roles: UsersIcon,
  feature_toggle: AdjustmentsHorizontalIcon,
}
