
CREATE TABLE `user_info` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `code` varchar(255) DEFAULT NULL,
  `gender` tinyint(3) UNSIGNED DEFAULT 1 COMMENT '1: Nam, 0: Nữ',
  `birthdate` datetime DEFAULT NULL,
  `birth_place` varchar(255) DEFAULT NULL,
  `national` varchar(255) DEFAULT NULL,
  `religion` varchar(255) DEFAULT NULL,
  `hometown` varchar(255) DEFAULT NULL,
  `identity` varchar(255) DEFAULT NULL,
  `identity_date` timestamp NULL DEFAULT NULL,
  `identity_place` varchar(255) DEFAULT NULL,
  `tax_code` varchar(255) DEFAULT NULL,
  `social_insurance_number` varchar(50) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `household` varchar(255) DEFAULT NULL,
  `bank_account` varchar(255) DEFAULT NULL,
  `bank` varchar(255) DEFAULT NULL,
  `start_working_date` timestamp NULL DEFAULT NULL,
  `working_place` varchar(255) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `department_name` varchar(255) DEFAULT NULL,
  `unit_name` varchar(255) DEFAULT NULL,
  `headquarter_name` varchar(255) DEFAULT NULL,
  `position_name` varchar(255) DEFAULT NULL,
  `concurrent_position_name` varchar(255) DEFAULT NULL,
  `department_id` bigint(20) UNSIGNED DEFAULT NULL,
  `company_id` bigint(20) UNSIGNED DEFAULT NULL,
  `health_insurance_code` varchar(50) DEFAULT NULL,
  `unemployment_insurance_number` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
